version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rails-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rails_network

  web:
    build: .
    container_name: rails-app
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://postgres:password@db:5432/rails_test_project_production
    depends_on:
      - redis
      - db
    networks:
      - rails_network
    volumes:
      - ./storage:/rails/storage

  db:
    image: postgres:15-alpine
    container_name: rails-postgres
    environment:
      - POSTGRES_DB=rails_test_project_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rails_network

volumes:
  redis_data:
  postgres_data:

networks:
  rails_network:
    driver: bridge
